apiVersion: v1
kind: Secret
metadata:
  name: private-chart
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogInBhc3MiCn0= 
type: kubernetes.io/dockerconfigjson
